name: coffea_202X_skimming
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - numpy
  - coffea
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - fsspec-xrootd
