name: coffea-env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - numpy=1.23.5
  - coffea==0.7.22
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - conda-forge::root
  - mpltern
  - scikit-learn
  - conda-forgecorrectionlib=2.5.0
